# Generated by Django 3.1.3 on 2020-11-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание статьи'),
        ),
    ]
